wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1630321566
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.12.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
